package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// EnvMap is a string->string map representing .env key-value pairs.
type EnvMap map[string]string

// envKeyOrder defines the canonical write order for .env keys.
var envKeyOrder = []string{
	"CONFIG_DIR",
	"LIBRARY_DIR",
	"WORK_DIR",
	"PUID",
	"PGID",
	"TZ",
	"WIREGUARD_PRIVATE_KEY",
	"SERVER_COUNTRIES",
	"PELICULA_PORT",
	"PELICULA_AUTH",
	"JELLYFIN_PASSWORD",
	"PROCULA_API_KEY",
	"TRANSCODING_ENABLED",
	"NOTIFICATIONS_ENABLED",
	"NOTIFICATIONS_MODE",
}

// ParseEnv reads a .env file and returns a map of key→value.
// Lines beginning with # or empty lines are skipped.
// Values may be optionally quoted with single or double quotes.
//
// Format contract: values are written as KEY="value" (double-quoted).
// Values must not contain double-quote characters or newlines — WriteEnv
// strips those characters before writing.
func ParseEnv(path string) (EnvMap, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	m := make(EnvMap)
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		idx := strings.IndexByte(line, '=')
		if idx < 0 {
			continue
		}
		key := strings.TrimSpace(line[:idx])
		val := strings.TrimSpace(line[idx+1:])

		// Strip surrounding quotes (single or double)
		if len(val) >= 2 {
			if (val[0] == '"' && val[len(val)-1] == '"') ||
				(val[0] == '\'' && val[len(val)-1] == '\'') {
				val = val[1 : len(val)-1]
			}
		}
		m[key] = val
	}
	return m, scanner.Err()
}

// WriteEnv writes the given EnvMap to path in canonical key order,
// with a header comment. Keys not in envKeyOrder are appended at the end
// in sorted-ish order (insertion order of map is not defined, so we just
// append extras).
func WriteEnv(path string, m EnvMap) error {
	// Back up existing file
	if _, err := os.Stat(path); err == nil {
		// best-effort backup — ignore errors
		_ = copyFile(path, path+".bak")
	}

	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "# Generated by pelicula setup")

	written := make(map[string]bool)
	for _, k := range envKeyOrder {
		if v, ok := m[k]; ok {
			fmt.Fprintf(f, "%s=\"%s\"\n", k, sanitizeEnvValue(v))
			written[k] = true
		}
	}
	// Write any extra keys not in the canonical order
	for k, v := range m {
		if !written[k] {
			fmt.Fprintf(f, "%s=\"%s\"\n", k, sanitizeEnvValue(v))
		}
	}
	return nil
}

// GetEnvVar reads a single key from the .env file at path.
// If the key is not found or the file cannot be read, defaultVal is returned.
func GetEnvVar(path, key, defaultVal string) string {
	m, err := ParseEnv(path)
	if err != nil {
		return defaultVal
	}
	if v, ok := m[key]; ok && v != "" {
		return v
	}
	return defaultVal
}

// SetEnvVar updates or appends a single key in the .env file at path.
func SetEnvVar(path, key, value string) error {
	m, err := ParseEnv(path)
	if err != nil {
		// If file doesn't exist, start fresh
		m = make(EnvMap)
	}
	m[key] = value
	return WriteEnv(path, m)
}

// MigrateEnv applies forward migrations to the .env file at path.
// Returns true if any migrations were applied.
func MigrateEnv(path string) (bool, error) {
	m, err := ParseEnv(path)
	if err != nil {
		return false, err
	}

	changed := false

	// Migration 1: MEDIA_DIR → LIBRARY_DIR + WORK_DIR
	if mediaDir, hasMD := m["MEDIA_DIR"]; hasMD && mediaDir != "" {
		if m["LIBRARY_DIR"] == "" {
			m["LIBRARY_DIR"] = mediaDir
			changed = true
		}
		if m["WORK_DIR"] == "" {
			m["WORK_DIR"] = mediaDir
			changed = true
		}
		if changed {
			info("Migrated MEDIA_DIR → LIBRARY_DIR and WORK_DIR in .env")
		}
	}

	// Migration 2: ensure default keys exist (only keys written by _write_env_file in bash)
	defaults := []struct{ key, val string }{
		{"TRANSCODING_ENABLED", "false"},
		{"NOTIFICATIONS_ENABLED", "false"},
		{"NOTIFICATIONS_MODE", "internal"},
	}
	for _, d := range defaults {
		if _, ok := m[d.key]; !ok {
			m[d.key] = d.val
			changed = true
		}
	}

	if changed {
		return true, WriteEnv(path, m)
	}
	return false, nil
}

// sanitizeEnvValue strips characters that would break the KEY="value" .env format:
// double-quote characters and newlines are removed.
func sanitizeEnvValue(v string) string {
	v = strings.ReplaceAll(v, `"`, "")
	v = strings.ReplaceAll(v, "\n", "")
	v = strings.ReplaceAll(v, "\r", "")
	return v
}

// copyFile is a simple file copy helper.
func copyFile(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	return os.WriteFile(dst, data, 0600)
}
