package main

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// exampleEnv is the map rendered into .env.example: documented defaults with
// blank secrets (generated by the next `pelicula up`).
func exampleEnv() EnvMap {
	return EnvMap{
		"CONFIG_DIR":            "/srv/pelicula/config",
		"LIBRARY_DIR":           "/srv/media",
		"WORK_DIR":              "/srv/media",
		"PUID":                  "1000",
		"PGID":                  "1000",
		"TZ":                    "UTC",
		"WIREGUARD_PRIVATE_KEY": "",
		"SERVER_COUNTRIES":      "Netherlands",
		"PELICULA_PORT":         "7354",
		"JELLYFIN_ADMIN_USER":   "admin",
		"JELLYFIN_PASSWORD":     "",
		"WEBHOOK_SECRET":        "",
		"GLUETUN_HTTP_USER":     "pelicula",
		"GLUETUN_HTTP_PASS":     "",
	}
}

func fullEnv() EnvMap {
	m := exampleEnv()
	m["WIREGUARD_PRIVATE_KEY"] = strings.Repeat("A", 43) + "="
	m["JELLYFIN_PASSWORD"] = "pw-0123456789abc"
	m["WEBHOOK_SECRET"] = "hook-secret"
	m["GLUETUN_HTTP_PASS"] = "gluetun-pass"
	m["SERVER_COUNTRIES"] = "New Zealand,Germany"
	return m
}

func TestEnvRoundTrip(t *testing.T) {
	path := filepath.Join(t.TempDir(), ".env")
	want := fullEnv()
	want["PELICULA_PROJECT_NAME"] = "mystack"
	want["CUSTOM_EXTRA"] = "keep me"

	if err := WriteEnv(path, want); err != nil {
		t.Fatal(err)
	}
	got, err := ParseEnv(path)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != len(want) {
		t.Errorf("round trip has %d keys, want %d: %v", len(got), len(want), got)
	}
	for k, v := range want {
		if got[k] != v {
			t.Errorf("%s = %q, want %q", k, got[k], v)
		}
	}
}

func TestWriteEnvKeepsEmptyLayoutKeys(t *testing.T) {
	path := filepath.Join(t.TempDir(), ".env")
	if err := WriteEnv(path, exampleEnv()); err != nil {
		t.Fatal(err)
	}
	got, _ := ParseEnv(path)
	// Empty keys must still be defined so compose never warns "variable is
	// not set" for them.
	for _, k := range []string{"WIREGUARD_PRIVATE_KEY", "JELLYFIN_PASSWORD", "WEBHOOK_SECRET", "GLUETUN_HTTP_PASS"} {
		if v, ok := got[k]; !ok || v != "" {
			t.Errorf("%s: present=%v value=%q, want present and empty", k, ok, v)
		}
	}
}

func TestWriteEnvProjectNameCommentedUntilSet(t *testing.T) {
	dir := t.TempDir()

	path := filepath.Join(dir, "unset.env")
	if err := WriteEnv(path, exampleEnv()); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(path)
	if !strings.Contains(string(data), "\n# PELICULA_PROJECT_NAME=pelicula\n") {
		t.Errorf("unset PELICULA_PROJECT_NAME should be a commented default:\n%s", data)
	}
	if m, _ := ParseEnv(path); m["PELICULA_PROJECT_NAME"] != "" {
		t.Errorf("commented PELICULA_PROJECT_NAME parsed as %q", m["PELICULA_PROJECT_NAME"])
	}

	m := exampleEnv()
	m["PELICULA_PROJECT_NAME"] = "other"
	path = filepath.Join(dir, "set.env")
	if err := WriteEnv(path, m); err != nil {
		t.Fatal(err)
	}
	data, _ = os.ReadFile(path)
	if !strings.Contains(string(data), "\nPELICULA_PROJECT_NAME=\"other\"\n") {
		t.Errorf("set PELICULA_PROJECT_NAME should be written:\n%s", data)
	}
}

func TestWriteEnvFileModeBackupAndAtomicity(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env")

	if err := WriteEnv(path, exampleEnv()); err != nil {
		t.Fatal(err)
	}
	if fi, err := os.Stat(path); err != nil || fi.Mode().Perm() != 0600 {
		t.Errorf(".env mode = %v (err %v), want 0600", fi.Mode().Perm(), err)
	}
	if fileExists(path + ".bak") {
		t.Error("first write must not create a backup")
	}

	first, _ := os.ReadFile(path)
	if err := WriteEnv(path, fullEnv()); err != nil {
		t.Fatal(err)
	}
	bak, err := os.ReadFile(path + ".bak")
	if err != nil || string(bak) != string(first) {
		t.Errorf(".env.bak should hold the previous content (err %v)", err)
	}

	entries, _ := os.ReadDir(dir)
	for _, e := range entries {
		if strings.Contains(e.Name(), ".tmp-") {
			t.Errorf("temp file left behind: %s", e.Name())
		}
	}
}

func TestParseEnvFormats(t *testing.T) {
	path := filepath.Join(t.TempDir(), ".env")
	content := `# comment
PLAIN=value
DOUBLE="with spaces"
SINGLE='single quoted'
INLINE=value # trailing comment
HASH_IN_QUOTES="a # b"
EMPTY=
export EXPORTED=yes
  SPACED = padded
DUP=first
DUP=second
no_equals_line
`
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		t.Fatal(err)
	}
	got, err := ParseEnv(path)
	if err != nil {
		t.Fatal(err)
	}
	want := EnvMap{
		"PLAIN": "value", "DOUBLE": "with spaces", "SINGLE": "single quoted",
		"INLINE": "value", "HASH_IN_QUOTES": "a # b", "EMPTY": "",
		"EXPORTED": "yes", "SPACED": "padded", "DUP": "second",
	}
	if len(got) != len(want) {
		t.Errorf("parsed %d keys, want %d: %v", len(got), len(want), got)
	}
	for k, v := range want {
		if got[k] != v {
			t.Errorf("%s = %q, want %q", k, got[k], v)
		}
	}
}

func TestParseEnvMissingFile(t *testing.T) {
	if _, err := ParseEnv(filepath.Join(t.TempDir(), "nope")); err == nil {
		t.Error("want an error for a missing file")
	}
}

func TestSanitizeEnvValue(t *testing.T) {
	if got := sanitizeEnvValue("a\"b\nc\r"); got != "abc" {
		t.Errorf("sanitizeEnvValue = %q, want %q", got, "abc")
	}
	// A hostile value must not be able to inject another variable.
	path := filepath.Join(t.TempDir(), ".env")
	m := exampleEnv()
	m["TZ"] = "UTC\"\nINJECTED=1"
	if err := WriteEnv(path, m); err != nil {
		t.Fatal(err)
	}
	got, _ := ParseEnv(path)
	if _, injected := got["INJECTED"]; injected {
		t.Error("newline in a value injected a new variable")
	}
}

func TestRenderEnvOtherKeysSorted(t *testing.T) {
	m := exampleEnv()
	m["ZED"] = "1"
	m["ALPHA"] = "2"
	out := renderEnv(m)
	a, z := strings.Index(out, "ALPHA="), strings.Index(out, "ZED=")
	if a < 0 || z < 0 || a > z {
		t.Errorf("extra keys should be kept and sorted:\n%s", out)
	}
	if renderEnv(m) != out {
		t.Error("renderEnv must be deterministic")
	}
}

func TestCompleteEnv(t *testing.T) {
	plat := Platform{UID: 1026, GID: 100, TZ: "Europe/Amsterdam"}
	m := EnvMap{"CONFIG_DIR": "/c", "LIBRARY_DIR": "/l", "WORK_DIR": "/w", "SERVER_COUNTRIES": "Germany"}
	set := completeEnv(m, plat)

	for key, want := range map[string]string{
		"PUID": "1026", "PGID": "100", "TZ": "Europe/Amsterdam",
		"SERVER_COUNTRIES": "Germany", // already set: untouched
		"PELICULA_PORT":    "7354", "JELLYFIN_ADMIN_USER": "admin", "GLUETUN_HTTP_USER": "pelicula",
		"CONFIG_DIR": "/c",
	} {
		if m[key] != want {
			t.Errorf("%s = %q, want %q", key, m[key], want)
		}
	}
	alnum := regexp.MustCompile(`^[A-Za-z0-9]+$`)
	for key, n := range map[string]int{"JELLYFIN_PASSWORD": 16, "WEBHOOK_SECRET": 32, "GLUETUN_HTTP_PASS": 32} {
		if len(m[key]) != n || !alnum.MatchString(m[key]) {
			t.Errorf("%s = %q, want %d alphanumeric chars", key, m[key], n)
		}
		if !containsKey(set, key) {
			t.Errorf("%s missing from the returned set %v", key, set)
		}
	}
	if containsKey(set, "SERVER_COUNTRIES") || containsKey(set, "CONFIG_DIR") {
		t.Errorf("set %v lists keys that were already present", set)
	}

	// Idempotent: a second pass changes nothing and keeps the secrets.
	pw := m["JELLYFIN_PASSWORD"]
	if again := completeEnv(m, plat); len(again) != 0 || m["JELLYFIN_PASSWORD"] != pw {
		t.Errorf("second completeEnv set %v / changed the password", again)
	}
}

func containsKey(list []string, k string) bool {
	for _, v := range list {
		if v == k {
			return true
		}
	}
	return false
}

func TestValidateEnv(t *testing.T) {
	good := fullEnv()
	if err := validateEnv(good); err != nil {
		t.Fatalf("valid env rejected: %v", err)
	}

	cases := []struct {
		name   string
		mutate func(EnvMap)
		want   string
	}{
		{"empty config", func(m EnvMap) { m["CONFIG_DIR"] = "" }, "CONFIG_DIR is empty"},
		{"relative library", func(m EnvMap) { m["LIBRARY_DIR"] = "media" }, "absolute"},
		{"tilde work", func(m EnvMap) { m["WORK_DIR"] = "~/media" }, "absolute"},
		{"bad port", func(m EnvMap) { m["PELICULA_PORT"] = "http" }, "PELICULA_PORT"},
		{"port range", func(m EnvMap) { m["PELICULA_PORT"] = "70000" }, "PELICULA_PORT"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			m := fullEnv()
			tc.mutate(m)
			err := validateEnv(m)
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Errorf("validateEnv error = %v, want it to mention %q", err, tc.want)
			}
		})
	}

	// A missing port means the default and is fine.
	delete(good, "PELICULA_PORT")
	if err := validateEnv(good); err != nil {
		t.Errorf("missing PELICULA_PORT should default: %v", err)
	}
}

func TestVPNEnabledAndProjectName(t *testing.T) {
	if vpnEnabled(EnvMap{}) || vpnEnabled(EnvMap{"WIREGUARD_PRIVATE_KEY": ""}) {
		t.Error("blank key must mean no VPN")
	}
	if !vpnEnabled(EnvMap{"WIREGUARD_PRIVATE_KEY": "k"}) {
		t.Error("a key must enable the VPN")
	}
	if got := envDefault(EnvMap{"A": ""}, "A", "d"); got != "d" {
		t.Errorf("envDefault = %q, want d", got)
	}
}

// TestEnvExampleMatchesLayout keeps .env.example identical to what the CLI
// generates. Regenerate it with: PELICULA_UPDATE_EXAMPLE=1 go test ./cmd/pelicula -run EnvExample
func TestEnvExampleMatchesLayout(t *testing.T) {
	path := filepath.Join("..", "..", ".env.example")
	want := renderEnv(exampleEnv())
	if os.Getenv("PELICULA_UPDATE_EXAMPLE") != "" {
		if err := os.WriteFile(path, []byte(want), 0644); err != nil {
			t.Fatal(err)
		}
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != want {
		t.Errorf(".env.example is out of date with the generated layout; run:\n  PELICULA_UPDATE_EXAMPLE=1 go test ./cmd/pelicula -run EnvExample")
	}

	// And it must define every key the contract requires.
	parsed, err := ParseEnv(path)
	if err != nil {
		t.Fatal(err)
	}
	for _, k := range []string{
		"CONFIG_DIR", "LIBRARY_DIR", "WORK_DIR", "PUID", "PGID", "TZ", "WIREGUARD_PRIVATE_KEY",
		"SERVER_COUNTRIES", "PELICULA_PORT", "JELLYFIN_ADMIN_USER", "JELLYFIN_PASSWORD",
		"WEBHOOK_SECRET", "GLUETUN_HTTP_USER", "GLUETUN_HTTP_PASS",
	} {
		if _, ok := parsed[k]; !ok {
			t.Errorf(".env.example lacks %s", k)
		}
	}
}
