package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestParseEnv(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env")

	content := `# Generated by pelicula setup
CONFIG_DIR="/volume1/config"
LIBRARY_DIR="/volume1/media"
WORK_DIR="/volume1/media"
PUID="1000"
PGID="1000"
TZ="America/New_York"
PELICULA_PORT="7354"
PELICULA_AUTH="jellyfin"
TRANSCODING_ENABLED=false
NOTIFICATIONS_MODE=internal
`
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		t.Fatal(err)
	}

	m, err := ParseEnv(path)
	if err != nil {
		t.Fatalf("ParseEnv error: %v", err)
	}

	tests := map[string]string{
		"CONFIG_DIR":          "/volume1/config",
		"LIBRARY_DIR":         "/volume1/media",
		"PUID":                "1000",
		"TZ":                  "America/New_York",
		"TRANSCODING_ENABLED": "false",
		"NOTIFICATIONS_MODE":  "internal",
	}
	for k, want := range tests {
		if got := m[k]; got != want {
			t.Errorf("key %q: got %q, want %q", k, got, want)
		}
	}
}

func TestParseEnvSingleQuotes(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env")
	if err := os.WriteFile(path, []byte("KEY='value with spaces'\n"), 0600); err != nil {
		t.Fatal(err)
	}
	m, err := ParseEnv(path)
	if err != nil {
		t.Fatal(err)
	}
	if got := m["KEY"]; got != "value with spaces" {
		t.Errorf("got %q, want %q", got, "value with spaces")
	}
}

func TestWriteEnv(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env")

	m := EnvMap{
		"CONFIG_DIR":          "/test/config",
		"LIBRARY_DIR":         "/test/lib",
		"WORK_DIR":            "/test/work",
		"PUID":                "1000",
		"PGID":                "1000",
		"TZ":                  "UTC",
		"WIREGUARD_PRIVATE_KEY": "abc123",
		"SERVER_COUNTRIES":    "Netherlands",
		"PELICULA_PORT":       "7354",
		"PELICULA_AUTH":       "jellyfin",
		"JELLYFIN_PASSWORD":   "pass-word-123",
		"PROCULA_API_KEY":     "key123",
		"TRANSCODING_ENABLED": "false",
		"NOTIFICATIONS_ENABLED": "false",
		"NOTIFICATIONS_MODE":  "internal",
	}

	if err := WriteEnv(path, m); err != nil {
		t.Fatalf("WriteEnv error: %v", err)
	}

	// Read back and verify
	m2, err := ParseEnv(path)
	if err != nil {
		t.Fatalf("ParseEnv after write: %v", err)
	}

	for k, want := range m {
		if got := m2[k]; got != want {
			t.Errorf("round-trip key %q: got %q, want %q", k, got, want)
		}
	}

	// Verify file permissions
	fi, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if fi.Mode().Perm() != 0600 {
		t.Errorf("file mode: got %o, want 0600", fi.Mode().Perm())
	}
}

func TestMigrateEnvMediaDir(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env")

	// Old-style .env with only MEDIA_DIR
	content := `CONFIG_DIR="/config"
MEDIA_DIR="/old/media"
PUID="1000"
PGID="1000"
TZ="UTC"
PELICULA_PORT="7354"
PELICULA_AUTH="off"
`
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		t.Fatal(err)
	}

	changed, err := MigrateEnv(path)
	if err != nil {
		t.Fatalf("MigrateEnv error: %v", err)
	}
	if !changed {
		t.Error("expected changed=true but got false")
	}

	m, err := ParseEnv(path)
	if err != nil {
		t.Fatal(err)
	}
	if m["LIBRARY_DIR"] != "/old/media" {
		t.Errorf("LIBRARY_DIR: got %q, want /old/media", m["LIBRARY_DIR"])
	}
	if m["WORK_DIR"] != "/old/media" {
		t.Errorf("WORK_DIR: got %q, want /old/media", m["WORK_DIR"])
	}
}

func TestMigrateEnvNoChange(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env")

	// Already migrated .env
	content := `CONFIG_DIR="/config"
LIBRARY_DIR="/media"
WORK_DIR="/media"
PUID="1000"
PGID="1000"
TZ="UTC"
PELICULA_PORT="7354"
PELICULA_AUTH="off"
JELLYFIN_ADMIN_USER="admin"
TRANSCODING_ENABLED="false"
NOTIFICATIONS_ENABLED="false"
NOTIFICATIONS_MODE="internal"
`
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		t.Fatal(err)
	}

	changed, err := MigrateEnv(path)
	if err != nil {
		t.Fatalf("MigrateEnv error: %v", err)
	}
	if changed {
		t.Error("expected changed=false but got true")
	}
}

func TestWriteEnvSanitizesQuotes(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env")

	m := EnvMap{
		"CONFIG_DIR": `/some/"path"`,
		"TZ":         "America/New_York\nINJECTED=evil",
	}
	if err := WriteEnv(path, m); err != nil {
		t.Fatalf("WriteEnv error: %v", err)
	}

	m2, err := ParseEnv(path)
	if err != nil {
		t.Fatalf("ParseEnv error: %v", err)
	}

	// Quotes should be stripped from CONFIG_DIR value
	if got := m2["CONFIG_DIR"]; got != "/some/path" {
		t.Errorf("CONFIG_DIR: got %q, want %q", got, "/some/path")
	}
	// Newline should be stripped — INJECTED key must not appear
	if _, ok := m2["INJECTED"]; ok {
		t.Error("INJECTED key must not appear — newline injection was not sanitized")
	}
}

func TestSetEnvVar(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env")

	m := EnvMap{
		"CONFIG_DIR":  "/config",
		"LIBRARY_DIR": "/media",
	}
	if err := WriteEnv(path, m); err != nil {
		t.Fatal(err)
	}

	if err := SetEnvVar(path, "LIBRARY_DIR", "/new/media"); err != nil {
		t.Fatal(err)
	}
	if err := SetEnvVar(path, "NEW_KEY", "new_value"); err != nil {
		t.Fatal(err)
	}

	m2, err := ParseEnv(path)
	if err != nil {
		t.Fatal(err)
	}
	if m2["LIBRARY_DIR"] != "/new/media" {
		t.Errorf("LIBRARY_DIR: got %q", m2["LIBRARY_DIR"])
	}
	if m2["NEW_KEY"] != "new_value" {
		t.Errorf("NEW_KEY: got %q", m2["NEW_KEY"])
	}
	if m2["CONFIG_DIR"] != "/config" {
		t.Errorf("CONFIG_DIR: got %q (should be unchanged)", m2["CONFIG_DIR"])
	}
}

func TestWriteEnvAdminUser(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env")

	m := EnvMap{
		"CONFIG_DIR":          "/config",
		"JELLYFIN_ADMIN_USER": "gwen",
		"JELLYFIN_PASSWORD":   "test-pass-123",
	}
	if err := WriteEnv(path, m); err != nil {
		t.Fatalf("WriteEnv error: %v", err)
	}
	m2, err := ParseEnv(path)
	if err != nil {
		t.Fatalf("ParseEnv error: %v", err)
	}
	if got := m2["JELLYFIN_ADMIN_USER"]; got != "gwen" {
		t.Errorf("JELLYFIN_ADMIN_USER: got %q, want %q", got, "gwen")
	}
}

func TestMigrateEnvAddsAdminUser(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env")

	content := `CONFIG_DIR="/config"
LIBRARY_DIR="/media"
WORK_DIR="/media"
PUID="1000"
PGID="1000"
TZ="UTC"
PELICULA_PORT="7354"
PELICULA_AUTH="jellyfin"
JELLYFIN_PASSWORD="old-pass-123"
TRANSCODING_ENABLED=false
NOTIFICATIONS_ENABLED=false
NOTIFICATIONS_MODE=internal
`
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		t.Fatal(err)
	}
	changed, err := MigrateEnv(path)
	if err != nil {
		t.Fatalf("MigrateEnv error: %v", err)
	}
	if !changed {
		t.Error("expected changed=true")
	}
	m, err := ParseEnv(path)
	if err != nil {
		t.Fatal(err)
	}
	if got := m["JELLYFIN_ADMIN_USER"]; got != "admin" {
		t.Errorf("JELLYFIN_ADMIN_USER: got %q, want %q", got, "admin")
	}
}
