package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
)

const tunDevice = "/dev/net/tun"

// tunOverrideYAML maps the host TUN device into gluetun, which needs it to
// bring up WireGuard. Generated, gitignored, and merged by Compose.buildArgs.
const tunOverrideYAML = `# Generated by "pelicula up" — do not edit (gitignored).
# Maps the host TUN device into gluetun, which needs it for WireGuard.
services:
  gluetun:
    devices:
      - /dev/net/tun:/dev/net/tun
`

// CheckTUN returns an error if /dev/net/tun is missing on Linux.
func CheckTUN() error { return checkTUN(runtime.GOOS, tunDevice) }

func checkTUN(goos, path string) error {
	if goos != "linux" {
		return nil
	}
	if !fileExists(path) {
		return fmt.Errorf("%s not found — create it with:\n  sudo mkdir -p /dev/net && sudo mknod /dev/net/tun c 10 200 && sudo chmod 600 /dev/net/tun", path)
	}
	return nil
}

// tunOverridePath is where the generated override lives.
func tunOverridePath(composeDir string) string {
	return filepath.Join(composeDir, "docker-compose.override.yml")
}

// writeTUNOverride writes the override unless it already has this content.
func writeTUNOverride(path string) error {
	if cur, err := os.ReadFile(path); err == nil && string(cur) == tunOverrideYAML {
		return nil
	}
	return os.WriteFile(path, []byte(tunOverrideYAML), 0644)
}

// ensureTUN prepares TUN support on Linux: it (re)writes the compose override
// and, when the VPN is enabled, verifies the device exists. Other platforms
// (Docker Desktop on macOS/Windows) need neither. Without a VPN gluetun never
// starts, so a missing device is not an error.
func ensureTUN(goos, composeDir, devicePath string, vpn bool) error {
	if goos != "linux" {
		return nil
	}
	if err := writeTUNOverride(tunOverridePath(composeDir)); err != nil {
		return fmt.Errorf("write compose override: %w", err)
	}
	if vpn {
		return checkTUN(goos, devicePath)
	}
	return nil
}
