// Package envfile provides shared .env read/write helpers used by the
// settings and setup handlers. The single .env file at /project/.env is
// bind-mounted, so atomic tmp+rename across the bind is impossible
// (cross-fs rename returns EXDEV). Concurrent access must be serialized
// by a shared sync.Mutex (see envMu wiring in bootstrap).
package envfile

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// Parse reads a key=value file, stripping quotes and skipping comments.
func Parse(path string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	result := make(map[string]string)
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		idx := strings.IndexByte(line, '=')
		if idx < 0 {
			continue
		}
		key := strings.TrimSpace(line[:idx])
		val := strings.TrimSpace(line[idx+1:])
		// Strip surrounding double quotes
		if len(val) >= 2 && val[0] == '"' && val[len(val)-1] == '"' {
			val = val[1 : len(val)-1]
		}
		result[key] = val
	}
	return result, scanner.Err()
}

// Write writes a key=value file in canonical order. Known keys are written
// first; any extra keys follow. NOT crash-safe — the destination is
// bind-mounted so atomic tmp+rename returns EXDEV. Callers MUST serialize
// via a shared mutex (see envMu wiring in bootstrap).
func Write(path string, vars map[string]string) error {
	// Canonical order matching the setup wizard (.env produced by internal/app/setup)
	order := []string{
		"CONFIG_DIR", "LIBRARY_DIR", "WORK_DIR",
		"PUID", "PGID", "TZ",
		"WIREGUARD_PRIVATE_KEY", "SERVER_COUNTRIES",
		"PELICULA_PORT",
		"PELICULA_OPEN_REGISTRATION",
		"JELLYFIN_ADMIN_USER", // legacy: kept for upgrade-path ordering
		"JELLYFIN_PASSWORD",   // legacy: kept for upgrade-path ordering
		"JELLYFIN_API_KEY",
		"JELLYFIN_PUBLISHED_URL",
		"PROCULA_API_KEY", "WEBHOOK_SECRET",
		"TRANSCODING_ENABLED",
		"NOTIFICATIONS_ENABLED", "NOTIFICATIONS_MODE",
		"PELICULA_SUB_LANGS",
		"REQUESTS_RADARR_PROFILE_ID", "REQUESTS_RADARR_ROOT",
		"REQUESTS_SONARR_PROFILE_ID", "REQUESTS_SONARR_ROOT",
		"REMOTE_MODE", "REMOTE_HOSTNAME",
		"REMOTE_HTTP_PORT", "REMOTE_HTTPS_PORT",
		"REMOTE_CERT_MODE", "REMOTE_LE_EMAIL", "REMOTE_LE_STAGING",
		"SEEDING_REMOVE_ON_COMPLETE",
		"SEARCH_MODE",
	}
	inOrder := make(map[string]bool, len(order))
	for _, k := range order {
		inOrder[k] = true
	}

	var sb strings.Builder
	sb.WriteString("# Generated by Pelicula setup wizard\n")
	for _, k := range order {
		v, ok := vars[k]
		if !ok {
			continue
		}
		writeLine(&sb, k, v)
	}
	// Preserve any extra keys not in the canonical list
	for k, v := range vars {
		if !inOrder[k] {
			writeLine(&sb, k, v)
		}
	}

	// Direct write (not tmp+rename): .env is bind-mounted as a single file
	// into the container, so a rename from an overlay-fs tmp would fail with
	// EXDEV and, even if it didn't, would replace the in-container mount
	// point rather than the host file.
	if err := os.WriteFile(path, []byte(sb.String()), 0600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func writeLine(sb *strings.Builder, k, v string) {
	// Booleans written unquoted; everything else double-quoted
	if v == "true" || v == "false" {
		fmt.Fprintf(sb, "%s=%s\n", k, v)
	} else {
		fmt.Fprintf(sb, "%s=\"%s\"\n", k, v)
	}
}
