// Package docker provides a typed HTTP client for the Docker socket proxy
// (tecnativa/docker-socket-proxy). It exposes only the container restart and
// log-fetch operations that pelicula-api requires, against an explicit
// allowlist of Compose service names.
package docker

import (
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"regexp"
	"time"
)

// allowedContainers is the explicit whitelist of Compose service names the
// admin endpoints may act on.  Keyed by service name (e.g. "sonarr"), not by
// the generated container name.  Defense-in-depth on top of the
// docker-socket-proxy allowlist.
var defaultAllowed = map[string]bool{
	"nginx":        true,
	"pelicula-api": true,
	"procula":      true,
	"sonarr":       true,
	"radarr":       true,
	"prowlarr":     true,
	"qbittorrent":  true,
	"jellyfin":     true,
	"bazarr":       true,
	"gluetun":      true,
}

var projectNameRE = regexp.MustCompile(`^[a-z0-9][a-z0-9_-]*$`)

// Client is a typed HTTP client for the Docker socket proxy.
type Client struct {
	baseURL     string
	projectName string
	allowed     map[string]bool
	httpClient  *http.Client
	// LogsFunc is the function used by Logs; replace in tests to inject fakes.
	LogsFunc func(name string, tail int, timestamps bool) ([]byte, error)
}

// New constructs a Client for the given Docker socket proxy base URL and
// Compose project name. projectName is validated against the same regex used
// by the original composeProject var; log.Fatalf is called on invalid input
// (same behaviour as before the refactor).
func New(baseURL, projectName string) *Client {
	if !projectNameRE.MatchString(projectName) {
		log.Fatalf("PELICULA_PROJECT_NAME %q is invalid: must match [a-z0-9][a-z0-9_-]*", projectName)
	}
	c := &Client{
		baseURL:     baseURL,
		projectName: projectName,
		allowed:     defaultAllowed,
		httpClient:  &http.Client{Timeout: 30 * time.Second},
	}
	c.LogsFunc = c.logs
	return c
}

// IsAllowed reports whether name (a Compose service name) is in the allowlist.
func (c *Client) IsAllowed(name string) bool {
	return c.allowed[name]
}

// AllowedNames returns the allowlist map. Callers may range over it to
// enumerate permitted service names; do not mutate the returned map.
func (c *Client) AllowedNames() map[string]bool {
	return c.allowed
}

// serviceToContainer maps a Compose service name to the Docker container name
// generated by Compose: <project>-<service>-1.
func (c *Client) serviceToContainer(svc string) string {
	return c.projectName + "-" + svc + "-1"
}

// Restart sends a restart request to the Docker Engine API for the named
// service (POST /containers/{container}/restart?t=5).
// name is a Compose service name; it is mapped to the generated container name.
func (c *Client) Restart(name string) error {
	url := c.baseURL + "/containers/" + c.serviceToContainer(name) + "/restart?t=5"
	req, err := http.NewRequest(http.MethodPost, url, nil)
	if err != nil {
		return err
	}
	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("docker restart %s: %w (is the Docker socket proxy reachable?)", name, err)
	}
	defer resp.Body.Close()
	io.Copy(io.Discard, resp.Body) //nolint:errcheck
	if resp.StatusCode >= 400 {
		return fmt.Errorf("docker restart %s: HTTP %d", name, resp.StatusCode)
	}
	return nil
}

// Logs fetches log lines for a service via LogsFunc. In production LogsFunc
// is bound to the internal logs implementation; tests replace it with a fake.
func (c *Client) Logs(name string, tail int, timestamps bool) ([]byte, error) {
	return c.LogsFunc(name, tail, timestamps)
}

// logs is the real implementation, used as the default value of LogsFunc.
// It fetches the last tail lines of stdout+stderr for a service.
// Docker multiplexes streams using an 8-byte framing header when the container
// has no TTY (our case); we strip those headers and return raw log bytes.
func (c *Client) logs(name string, tail int, timestamps bool) ([]byte, error) {
	if tail <= 0 || tail > 500 {
		tail = 200
	}
	tsParam := "0"
	if timestamps {
		tsParam = "1"
	}
	url := fmt.Sprintf("%s/containers/%s/logs?stdout=1&stderr=1&tail=%d&timestamps=%s",
		c.baseURL, c.serviceToContainer(name), tail, tsParam)
	resp, err := c.httpClient.Get(url)
	if err != nil {
		return nil, fmt.Errorf("docker logs %s: %w (is the Docker socket proxy reachable?)", name, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("docker logs %s: HTTP %d", name, resp.StatusCode)
	}
	return demuxDockerLogs(resp.Body)
}

// NetIO holds the receive/transmit byte counters for a single network interface.
type NetIO struct {
	RxBytes uint64 `json:"rx_bytes"`
	TxBytes uint64 `json:"tx_bytes"`
}

// StatsResponse captures the fields we need from Docker's one-shot stats JSON.
// Containers sharing another container's network namespace (e.g. qbittorrent,
// prowlarr sharing gluetun) return Networks: null — callers must handle nil.
type StatsResponse struct {
	Read     time.Time        `json:"read"`
	Networks map[string]NetIO `json:"networks"`
}

// Stats fetches a one-shot stats snapshot for the named Compose service.
// GET /containers/{container}/stats?stream=false
func (c *Client) Stats(name string) (*StatsResponse, error) {
	url := c.baseURL + "/containers/" + c.serviceToContainer(name) + "/stats?stream=false"
	resp, err := c.httpClient.Get(url)
	if err != nil {
		return nil, fmt.Errorf("docker stats %s: %w", name, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("docker stats %s: HTTP %d", name, resp.StatusCode)
	}
	var s StatsResponse
	if err := json.NewDecoder(resp.Body).Decode(&s); err != nil {
		return nil, fmt.Errorf("docker stats %s: decode: %w", name, err)
	}
	return &s, nil
}

// demuxDockerLogs strips the Docker stream multiplexing headers and returns
// the concatenated log payload.
//
// Frame format: [stream(1), 0,0,0, size(4 BE)] followed by `size` payload bytes.
// stream: 1=stdout, 2=stderr (we include both).
//
// Total output is capped at maxLogBytes to bound memory use against a
// misbehaving proxy or unexpectedly large frames.
const maxLogBytes = 5 << 20 // 5 MiB

func demuxDockerLogs(r io.Reader) ([]byte, error) {
	var out []byte
	hdr := make([]byte, 8)
	for {
		_, err := io.ReadFull(r, hdr)
		if err == io.EOF || err == io.ErrUnexpectedEOF {
			break
		}
		if err != nil {
			return out, err
		}
		size := binary.BigEndian.Uint32(hdr[4:8])
		if size == 0 {
			continue
		}
		if len(out)+int(size) > maxLogBytes {
			break
		}
		chunk := make([]byte, size)
		if _, err := io.ReadFull(r, chunk); err != nil {
			break
		}
		out = append(out, chunk...)
	}
	return out, nil
}
