services:
  cloudflared:
    image: cloudflare/cloudflared:2026.3.0
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - pelicula
    depends_on:
      - nginx

networks:
  pelicula:
    name: pelicula
    external: true
