package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"net/url"
	"os"
	"strings"
	"sync"
)

const envPath = "/project/.env"
const maskedValue = "••••••••"

// envMu serialises reads and writes to the .env file so concurrent admin
// requests cannot interleave their read-modify-write cycles.
var envMu sync.Mutex

// SettingsResponse is returned by GET /api/pelicula/settings.
type SettingsResponse struct {
	WireguardKey         string `json:"wireguard_key"`
	Country              string `json:"country"`
	ConfigDir            string `json:"config_dir"`
	LibraryDir           string `json:"library_dir"`
	WorkDir              string `json:"work_dir"`
	Port                 string `json:"port"`
	AuthMode             string `json:"auth_mode"`
	Password             string `json:"password"`
	ProculaAPIKey        string `json:"procula_api_key"`
	JellyseerrEnabled    string `json:"jellyseerr_enabled"`
	TranscodingEnabled   string `json:"transcoding_enabled"`
	NotificationsEnabled string `json:"notifications_enabled"`
	NotificationsMode    string `json:"notifications_mode"`
	SubLangs             string `json:"sub_langs"`
	TZ                   string `json:"tz"`
	PUID                 string `json:"puid"`
	PGID                 string `json:"pgid"`
}

// parseEnvFile reads a .env file and returns a key→value map.
// Handles quoted values, comments (#), and blank lines.
func parseEnvFile(path string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	result := make(map[string]string)
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		idx := strings.IndexByte(line, '=')
		if idx < 0 {
			continue
		}
		key := strings.TrimSpace(line[:idx])
		val := strings.TrimSpace(line[idx+1:])
		// Strip surrounding double quotes
		if len(val) >= 2 && val[0] == '"' && val[len(val)-1] == '"' {
			val = val[1 : len(val)-1]
		}
		result[key] = val
	}
	return result, scanner.Err()
}

// writeEnvFile atomically writes a .env file from the provided key-value map.
// Known keys are written in canonical order; any extra keys follow.
// Caller must hold envMu.
func writeEnvFile(path string, vars map[string]string) error {
	// Canonical order matching handleSetupSubmit
	order := []string{
		"CONFIG_DIR", "LIBRARY_DIR", "WORK_DIR",
		"PUID", "PGID", "TZ",
		"WIREGUARD_PRIVATE_KEY", "SERVER_COUNTRIES",
		"PELICULA_PORT", "PELICULA_AUTH", "PELICULA_PASSWORD",
		"PROCULA_API_KEY", "WEBHOOK_SECRET",
		"JELLYSEERR_ENABLED", "TRANSCODING_ENABLED",
		"NOTIFICATIONS_ENABLED", "NOTIFICATIONS_MODE",
		"PELICULA_SUB_LANGS",
	}
	inOrder := make(map[string]bool, len(order))
	for _, k := range order {
		inOrder[k] = true
	}

	var sb strings.Builder
	sb.WriteString("# Generated by Pelicula setup wizard\n")
	for _, k := range order {
		v, ok := vars[k]
		if !ok {
			continue
		}
		writeLine(&sb, k, v)
	}
	// Preserve any extra keys not in the canonical list (e.g. JELLYFIN_PASSWORD)
	for k, v := range vars {
		if !inOrder[k] {
			writeLine(&sb, k, v)
		}
	}

	// Direct write (not tmp+rename): .env is bind-mounted as a single file
	// into the container, so a rename from an overlay-fs tmp would fail with
	// EXDEV and, even if it didn't, would replace the in-container mount
	// point rather than the host file.
	if err := os.WriteFile(path, []byte(sb.String()), 0600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func writeLine(sb *strings.Builder, k, v string) {
	// Booleans written unquoted; everything else double-quoted
	if v == "true" || v == "false" {
		fmt.Fprintf(sb, "%s=%s\n", k, v)
	} else {
		fmt.Fprintf(sb, "%s=\"%s\"\n", k, v)
	}
}

func handleSettings(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		handleSettingsGet(w, r)
	case http.MethodPost:
		handleSettingsUpdate(w, r)
	default:
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
	}
}

func handleSettingsGet(w http.ResponseWriter, r *http.Request) {
	envMu.Lock()
	vars, err := parseEnvFile(envPath)
	envMu.Unlock()

	if err != nil {
		if os.IsNotExist(err) {
			http.Error(w, "not configured", http.StatusNotFound)
			return
		}
		slog.Error("failed to read .env", "error", err)
		http.Error(w, "failed to read config", http.StatusInternalServerError)
		return
	}

	resp := SettingsResponse{
		WireguardKey:         maskedValue,
		Country:              vars["SERVER_COUNTRIES"],
		ConfigDir:            vars["CONFIG_DIR"],
		LibraryDir:           vars["LIBRARY_DIR"],
		WorkDir:              vars["WORK_DIR"],
		Port:                 vars["PELICULA_PORT"],
		AuthMode:             vars["PELICULA_AUTH"],
		Password:             maskedValue,
		ProculaAPIKey:        maskedValue,
		JellyseerrEnabled:    vars["JELLYSEERR_ENABLED"],
		TranscodingEnabled:   vars["TRANSCODING_ENABLED"],
		NotificationsEnabled: vars["NOTIFICATIONS_ENABLED"],
		NotificationsMode:    vars["NOTIFICATIONS_MODE"],
		SubLangs:             vars["PELICULA_SUB_LANGS"],
		TZ:                   vars["TZ"],
		PUID:                 vars["PUID"],
		PGID:                 vars["PGID"],
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(resp)
}

func handleSettingsUpdate(w http.ResponseWriter, r *http.Request) {
	if !isLocalOrigin(r.Header.Get("Origin")) {
		http.Error(w, "forbidden", http.StatusForbidden)
		return
	}

	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
	var req SettingsResponse
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "invalid JSON: "+err.Error(), http.StatusBadRequest)
		return
	}

	// Validate non-sensitive string fields
	toCheck := []struct{ name, val string }{
		{"country", req.Country},
		{"config_dir", req.ConfigDir},
		{"library_dir", req.LibraryDir},
		{"work_dir", req.WorkDir},
		{"port", req.Port},
		{"tz", req.TZ},
		{"sub_langs", req.SubLangs},
	}
	for _, c := range toCheck {
		if c.val != "" && strings.ContainsAny(c.val, "\"\n\r") {
			http.Error(w, c.name+" contains invalid characters", http.StatusBadRequest)
			return
		}
	}

	// Validate WireGuard key only if being changed
	if req.WireguardKey != "" && req.WireguardKey != maskedValue {
		key := strings.TrimSpace(req.WireguardKey)
		if len(key) != 44 || key[43] != '=' {
			http.Error(w, "wireguard_key must be a 44-character base64 WireGuard private key", http.StatusBadRequest)
			return
		}
		req.WireguardKey = key
	}

	// Validate auth mode if being changed
	if req.AuthMode != "" {
		switch req.AuthMode {
		case "off", "true", "password", "users":
			// valid
		default:
			http.Error(w, "auth_mode must be one of: off, password, users", http.StatusBadRequest)
			return
		}
	}

	// Validate password if being changed
	if req.Password != "" && req.Password != maskedValue {
		if strings.ContainsAny(req.Password, "\"\n\r") {
			http.Error(w, "password contains invalid characters", http.StatusBadRequest)
			return
		}
	}

	envMu.Lock()
	defer envMu.Unlock()

	vars, err := parseEnvFile(envPath)
	if err != nil {
		slog.Error("failed to read .env for update", "error", err)
		http.Error(w, "failed to read config", http.StatusInternalServerError)
		return
	}

	// Merge changed fields; skip masked/empty values
	if req.WireguardKey != "" && req.WireguardKey != maskedValue {
		vars["WIREGUARD_PRIVATE_KEY"] = req.WireguardKey
	}
	if req.Country != "" {
		vars["SERVER_COUNTRIES"] = req.Country
	}
	if req.ConfigDir != "" {
		vars["CONFIG_DIR"] = req.ConfigDir
	}
	if req.LibraryDir != "" {
		vars["LIBRARY_DIR"] = req.LibraryDir
	}
	if req.WorkDir != "" {
		vars["WORK_DIR"] = req.WorkDir
	}
	if req.Port != "" {
		vars["PELICULA_PORT"] = req.Port
	}
	if req.AuthMode != "" {
		vars["PELICULA_AUTH"] = req.AuthMode
	}
	if req.Password != "" && req.Password != maskedValue {
		vars["PELICULA_PASSWORD"] = req.Password
	}
	if req.TZ != "" {
		vars["TZ"] = req.TZ
	}
	if req.PUID != "" {
		vars["PUID"] = req.PUID
	}
	if req.PGID != "" {
		vars["PGID"] = req.PGID
	}
	if req.JellyseerrEnabled != "" {
		vars["JELLYSEERR_ENABLED"] = req.JellyseerrEnabled
	}
	if req.TranscodingEnabled != "" {
		vars["TRANSCODING_ENABLED"] = req.TranscodingEnabled
	}
	if req.NotificationsEnabled != "" {
		vars["NOTIFICATIONS_ENABLED"] = req.NotificationsEnabled
	}
	if req.NotificationsMode != "" {
		vars["NOTIFICATIONS_MODE"] = req.NotificationsMode
	}
	if req.SubLangs != "" {
		vars["PELICULA_SUB_LANGS"] = req.SubLangs
	}

	if err := writeEnvFile(envPath, vars); err != nil {
		slog.Error("failed to write .env", "error", err)
		http.Error(w, "failed to write config", http.StatusInternalServerError)
		return
	}

	slog.Info("settings updated via browser wizard", "component", "settings")
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]any{"status": "ok", "restart_required": true})
}

func handleSettingsReset(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	if !isLocalOrigin(r.Header.Get("Origin")) {
		http.Error(w, "forbidden", http.StatusForbidden)
		return
	}

	r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
	var req SetupRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "invalid JSON: "+err.Error(), http.StatusBadRequest)
		return
	}

	// Sanitize all string fields
	for _, check := range []struct{ name, val string }{
		{"wireguard_key", req.WireguardKey},
		{"country", req.Country},
		{"config_dir", req.ConfigDir},
		{"library_dir", req.LibraryDir},
		{"work_dir", req.WorkDir},
		{"port", req.Port},
		{"password", req.Password},
	} {
		if strings.ContainsAny(check.val, "\"\n\r") {
			http.Error(w, check.name+" contains invalid characters", http.StatusBadRequest)
			return
		}
	}

	key := strings.TrimSpace(req.WireguardKey)
	if key == "" {
		http.Error(w, "wireguard_key is required", http.StatusBadRequest)
		return
	}
	if len(key) != 44 || key[43] != '=' {
		http.Error(w, "wireguard_key must be a 44-character base64 WireGuard private key", http.StatusBadRequest)
		return
	}
	req.WireguardKey = key

	if req.Country == "" {
		req.Country = "Netherlands"
	}
	if req.Port == "" {
		req.Port = "7354"
	}
	if req.ConfigDir == "" {
		req.ConfigDir = envOr("HOST_CONFIG_DIR", "./config")
	}
	if req.LibraryDir == "" {
		req.LibraryDir = envOr("HOST_LIBRARY_DIR", "~/media")
	}
	if req.WorkDir == "" {
		req.WorkDir = envOr("HOST_WORK_DIR", "~/media")
	}

	password := req.Password
	authMode := "off"
	if req.AuthEnabled {
		authMode = "true"
		if password == "" {
			password = generateReadablePassword()
		}
	}

	envMu.Lock()
	defer envMu.Unlock()

	existing, _ := parseEnvFile(envPath)
	puid := envOr("HOST_PUID", orDefault(existing["PUID"], "1000"))
	pgid := envOr("HOST_PGID", orDefault(existing["PGID"], "1000"))
	tz := envOr("HOST_TZ", orDefault(existing["TZ"], "America/New_York"))
	proculaKey := generateAPIKey()
	// Preserve existing WEBHOOK_SECRET if present so autowired webhooks keep working
	webhookSecret := orDefault(existing["WEBHOOK_SECRET"], generateAPIKey())

	vars := map[string]string{
		"CONFIG_DIR":            req.ConfigDir,
		"LIBRARY_DIR":           req.LibraryDir,
		"WORK_DIR":              req.WorkDir,
		"PUID":                  puid,
		"PGID":                  pgid,
		"TZ":                    tz,
		"WIREGUARD_PRIVATE_KEY": req.WireguardKey,
		"SERVER_COUNTRIES":      req.Country,
		"PELICULA_PORT":         req.Port,
		"PELICULA_AUTH":         authMode,
		"PELICULA_PASSWORD":     password,
		"PROCULA_API_KEY":       proculaKey,
		"WEBHOOK_SECRET":        webhookSecret,
		"JELLYSEERR_ENABLED":    "false",
		"TRANSCODING_ENABLED":   "false",
		"NOTIFICATIONS_ENABLED": "false",
		"NOTIFICATIONS_MODE":    "internal",
		"PELICULA_SUB_LANGS":    "en",
	}

	if err := writeEnvFile(envPath, vars); err != nil {
		slog.Error("failed to write .env during reset", "error", err)
		http.Error(w, "failed to write config", http.StatusInternalServerError)
		return
	}

	slog.Info("settings reset via browser wizard", "component", "settings")
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]any{
		"status":           "ok",
		"restart_required": true,
		"password":         password,
	})
}

// isLocalOrigin returns true if the request Origin is a localhost or
// private-network address. Parses the origin as a URL and checks the hostname
// to prevent substring-match bypasses. Returns false for empty Origin so that
// unauthenticated curl requests (no Origin header) cannot bypass CSRF checks.
func isLocalOrigin(origin string) bool {
	if origin == "" {
		return false
	}
	u, err := url.Parse(origin)
	if err != nil {
		return false
	}
	host := u.Hostname()
	if host == "localhost" || host == "127.0.0.1" || host == "::1" {
		return true
	}
	ip := net.ParseIP(host)
	if ip == nil {
		return false
	}
	for _, cidr := range []string{
		"192.168.0.0/16",
		"10.0.0.0/8",
		"172.16.0.0/12",
	} {
		_, network, _ := net.ParseCIDR(cidr)
		if network.Contains(ip) {
			return true
		}
	}
	return false
}

func orDefault(s, fallback string) string {
	if s != "" {
		return s
	}
	return fallback
}
