proxy_set_header Accept-Encoding "";
sub_filter '</head>' '<link rel="stylesheet" href="/theme.css"><link rel="stylesheet" href="/service-overrides.css"></head>';
sub_filter_once on;
sub_filter_types text/html;
